### ISSUE TITLE
gh-packages based deployment

### ISSUE THREAD

**Issue by FrankGrimm** [FrankGrimm/omen#36]
The package build through github's packages feature based on `Dockerfile.prod` works locally but has permission issues when pulled:

```bash
omen_1  | Traceback (most recent call last):
omen_1  |   File "/usr/local/bin/gunicorn", line 8, in <module>
omen_1  |     sys.exit(run())
omen_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in run
omen_1  |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
omen_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 228, in run
omen_1  |     super().run()
omen_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 72, in run
omen_1  |     Arbiter(self).run()
omen_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 58, in __init__
omen_1  |     self.setup(app)
omen_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 93, in setup
omen_1  |     self.log = self.cfg.logger_class(app.cfg)
omen_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/glogging.py", line 195, in __init__
omen_1  |     self.setup(cfg)
omen_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/glogging.py", line 207, in setup
omen_1  |     self.logfile = open(cfg.errorlog, 'a+')
omen_1  | PermissionError: [Errno 13] Permission denied: '/home/omenuser/logs/error_log.log'
```

The above was performed with the following service definition in `examples/docker-compose.yml`:

```yml
version: '3'
services:
    omen:
        image: docker.pkg.github.com/frankgrimm/omen/omen-prod:latest
        restart: always
        ports:
            - "5000:5000"
        volumes:
            - ${PWD}/app:/home/omenuser/app/app
            - ${PWD}/logs:/home/omenuser/logs
            - ${PWD}/config.json:/home/omenuser/app/config.json
        environment:
            - LOGLEVEL=debug
            - WORKERS_PER_CORE=1
```
